/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IdeaNFT__factory } from "./IdeaNFT__factory";
export { OrphanPlatform__factory } from "./OrphanPlatform__factory";
