/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdeaNFT } from "./IdeaNFT";
export type { OrphanPlatform } from "./OrphanPlatform";
export * as factories from "./factories";
export { IdeaNFT__factory } from "./factories/IdeaNFT__factory";
export { OrphanPlatform__factory } from "./factories/OrphanPlatform__factory";
